version: '3'

services:
  data_source:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local
#    networks:
#      - lab7_mynetwork

  model:
    image: ghfranjabour/model-service:latest
    container_name: model
    build:
      context: src/.
      dockerfile: Dockerfile
    ports:
      - "4040:4040"  # Spark UI
    environment:
      - SPARK_MODE=master
    networks:
      - local
#    networks:
#      - lab7_mynetwork

  datamart:
    image: ghfranjabour/datamart-service:latest
    build:
      context: datamart/.
      dockerfile: Dockerfile
    container_name: datamart
    ports:
      - "9000:9000"  # Expose API for querying
    networks:
      - local
#    networks:
#      - lab7_mynetwork


#networks:
#  lab7_mynetwork:
#    external: true
networks:
  local:
    driver: bridge
volumes:
  oracle-data:
  oracle-backup:
