apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datamart
  template:
    metadata:
      labels:
        app: datamart
    spec:
      containers:
      - name: datamart
        image: ghfranjabour/datamart-service:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: datamart-service
spec:
  type: NodePort
  selector:
    app: datamart
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30003
