apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-source-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-source
  template:
    metadata:
      labels:
        app: data-source
    spec:
      containers:
      - name: data-source
        image: ghfranjabour/oracle-enterprise:21.3.0.0
        ports:
        - containerPort: 1521
        env:
          - name: ORACLE_SID
            value: "ORCLCDB"
          - name: ORACLE_PDB
            value: "ORCLPDB1"
          - name: ORACLE_PWD
            value: "Oracle_123"
---
apiVersion: v1
kind: Service
metadata:
  name: data-source-service
spec:
  type: NodePort
  selector:
    app: data-source
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 30002
