apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: ghfranjabour/model-service:latest
        ports:
        - containerPort: 4040
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: NodePort
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30001
